forcedotcom/salesforcedx-vscode-automation-tests

.prettierrc
test/environmentSettings.ts
test/specs/anInitialSuite.e2e.ts
test/specs/apexLsp.e2e.ts
test/specs/apexReplayDebugger.e2e.ts
test/specs/auraLsp.e2e.ts
test/specs/authentication.e2e.ts
test/specs/debugApexTests.e2e.ts
test/specs/lwcLsp.e2e.ts
test/specs/manifestBuilder.e2e.ts
test/specs/pushAndPull.e2e.ts
test/specs/runApexTests.e2e.ts
test/specs/trailApexReplayDebugger.e2e.ts
test/specs/visualforceLsp.e2e.ts
test/testSetup.ts
test/utilities/commandPrompt.ts
test/utilities/extensionUtils.ts
test/utilities/index.ts
test/utilities/lwcUtils.ts
test/utilities/miscellaneous.ts
test/utilities/statusBar.ts

fixes for some flappers

---

.gitignore
test/specs/templates.e2e.ts
test/wdio.conf.ts

**What does this PR do?**
This PR adds additional coverage for the following templates:
* Apex Class
* Apex Trigger
* Aura App
* Aura Interface
* Visualforce Component
* Visualforce Page
For the deets, see https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001Pq8g5YAB/view

feat: add additional template coverage

---

test/specs/apexLsp.e2e.ts
test/utilities/apexUtils.ts
test/utilities/commandPrompt.ts

Refactor of apexUtils.ts and some waits around apexLsp so the suite passes
- [5662503386](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5662503386)
- [5662610742](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5662610742)
- [5662887724](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5662887724)
- [5662886537](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5662886537)
@W-13743983@
@W-13743939@

Fixes for ApexLSP on remote

---

test/specs/deployAndRetrieve.e2e.ts

Just a small refactor for the usage of browser.keys, as I recently found out that I could have just written the whole sentence and not letter by letter
Successful run: [261](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5845441308) ✅

Refactor for browser.keys

---

test/specs/trailApexReplayDebugger.e2e.ts

refactor for trailApexReplayDebugger.e2e.ts passing on GHA
@W-13744011@

Fixes for Trail Apex Replay Debugger on GHA

---

.vscode/settings.json
README.md

Update README.md in e2e automation tests repo with current requirements and steps to follow to run the tests locally
@W-14697707@

chore: update readme

---

test/specs/runApexTests.e2e.ts

Implement test for SFDX: Run Apex Tests > All Tests
@W-14344610@

feat: run all apex tests from command palette

---

.vscode/tasks.json
test/setup/anInitialSetUp.e2e.ts
test/specs/pushAndPull.e2e.ts
test/testSetup.ts

Transition from sfdx to sf style commands
@W-14700725@
Test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/8530711688

fix: sfdx to sf

---

test/specs/miscellaneous.e2e.ts

Implements tests for using out-of-the-box apex and lwc snippets
@W-14344606@
Test runs: 
- https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9016388666/job/24772889779
- https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9016715893/job/24775353364

feat: apex and lwc snippets

---

test/specs/apexReplayDebugger.e2e.ts

Implement test for SFDX: Launch Apex Replay Debugger from Current File
[skip-validate-pr]
Test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9025691296/job/24801808352 ✅

feat: launch ard from current test class

---

test/specs/debugApexTests.e2e.ts
test/specs/runApexTests.e2e.ts
test/specs/runLwcTests.e2e.ts
test/utilities/lwcUtils.ts
test/utilities/sideBar.ts
test/utilities/terminalView.ts

Implement tests for running LWC tests
[W-14866664](https://gus.lightning.force.com/a07EE00001iebi5YAA)
Test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9036615776/job/24833842612 ✅

feat: run lwc tests

---

test/specs/anInitialSuite.e2e.ts
test/specs/authentication.e2e.ts
test/specs/deployAndRetrieve.e2e.ts
test/specs/pushAndPull.e2e.ts
test/testSetup.ts
test/utilities/miscellaneous.ts

Implement E2E tests for view changes commands
This PR also refactors pushAndPull.e2e.ts and deplloyAndRetrieve.e2e.ts files
[W-14866436](https://gus.lightning.force.com/a07EE00001ie4FbYAI)
Test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9127010762/job/25096411392 ✅

feat: view local changes and refactor push and pull, deploy and retrieve e2e files

---

test/specs/deployAndRetrieve.e2e.ts
test/specs/manifestBuilder.e2e.ts
test/specs/orgBrowser.e2e.ts

Updates deploy and retrieve commands after https://github.com/forcedotcom/salesforcedx-vscode/pull/5609
[W-15355718](https://gus.lightning.force.com/a07EE00001nBZRxYAO)
Test run https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9208205585 ✅

fix: update commands for deploy and retrieve

---

test/specs/apexLsp.e2e.ts
test/specs/apexReplayDebugger.e2e.ts
test/specs/debugLwcTests.e2e.ts
test/specs/lwcLsp.e2e.ts
test/specs/orgBrowser.e2e.ts
test/specs/trailApexReplayDebugger.e2e.ts
test/utilities/outputView.ts

- Fixed import for CMD_KEY
- Removed commented imports
@W-16171600@
Test run: [LWC End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9801340245)

fix: make debug lwc tests run against testesm branch

---

test/testSetup.ts

Modify E2E TestSetup so it will not fail if scratch org is not present

---

package-lock.json
package.json
test/selfSpecs/notifications.test.ts
test/selfSpecs/settings.test.ts
test/specs/apexReplayDebugger.e2e.ts
test/specs/authentication.e2e.ts
test/specs/debugApexTests.e2e.ts
test/specs/deployAndRetrieve.e2e.ts
test/specs/manifestBuilder.e2e.ts
test/specs/orgBrowser.e2e.ts
test/specs/pushAndPull.e2e.ts
test/specs/runApexTests.e2e.ts
test/specs/sObjectsDefinitions.e2e.ts
test/specs/templates.e2e.ts
test/specs/trailApexReplayDebugger.e2e.ts
test/testSetup.ts
test/utilities/commandPrompt.ts
test/utilities/constants.ts
test/utilities/miscellaneous.ts
test/utilities/notifications.ts
test/utilities/outputView.ts
test/utilities/screenshot.ts
test/utilities/settings.ts

chore: fix deploy retrieve tests for esm

---

test/environmentSettings.ts
test/selfSpecs/useExistingProject.test.ts
test/specs/apexLsp.e2e.ts
test/specs/apexReplayDebugger.e2e.ts
test/specs/authentication.e2e.ts
test/specs/debugApexTests.e2e.ts
test/specs/deployAndRetrieve.e2e.ts
test/specs/manifestBuilder.e2e.ts
test/specs/orgBrowser.e2e.ts
test/specs/pushAndPull.e2e.ts
test/specs/runApexTests.e2e.ts
test/specs/sObjectsDefinitions.e2e.ts
test/specs/templates.e2e.ts
test/specs/trailApexReplayDebugger.e2e.ts
test/testSetup.ts
test/utilities/cliCommands.ts
test/utilities/commandPrompt.ts
test/utilities/constants.ts
test/utilities/index.ts
test/utilities/miscellaneous.ts
test/utilities/orgBrowser.ts
test/utilities/statusBar.ts
test/utilities/workbench.ts
test/wdio.conf.ts

fix: org browser e2e

---

test/specs/anInitialSuite.e2e.ts
test/testSetup.ts
test/utilities/cliCommands.ts
test/utilities/miscellaneous.ts

- Created a new project with cli 
- Open up the project with command: `File: Open Folder...`

feat: use cli to generate project rather than UI

---

test/specs/debugApexTests.e2e.ts
test/specs/debugLwcTests.e2e.ts
test/specs/runApexTests.e2e.ts
test/specs/runLwcTests.e2e.ts
test/utilities/index.ts
test/utilities/sideBar.ts
test/utilities/testsUtils.ts

Refactor to reduce dupe code in lwc and apex tests
@W-16688177@
[LWC End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10765914393) ✅ 
[Apex End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10765912870) ✅

Refactor Apex and LWC tests

---

test/utilities/cliCommands.ts

Fixes installation for lwc tests deps
Test run:
- [LWC End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10834694073) ✅

Fix for LWC tests

---

test/specs/debugLwcTests.e2e.ts
test/specs/runApexTests.e2e.ts
test/specs/runLwcTests.e2e.ts
test/specs/sObjectsDefinitions.e2e.ts
test/utilities/commandPrompt.ts
test/utilities/notifications.ts
test/utilities/outputView.ts
test/utilities/testsUtils.ts

- Adds logging in each step and right validation for presence of folders for sObjectsDefinitions.e2e.ts file
@W-16825635@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/11022085552) ✅

fix: validate sobjects related folders
