forcedotcom/salesforcedx-vscode-automation-tests

test/environmentSettings.ts
test/specs/anInitialSuite.e2e.ts
test/specs/apexLsp.e2e.ts
test/specs/auraLsp.e2e.ts
test/specs/deployAndRetrieve.e2e.ts
test/specs/lwcLsp.e2e.ts
test/specs/visualForceLsp.e2e.ts
test/testSetup.ts
test/wdio.conf.ts

* Added placeholders for additional test suites:
test/specs/apexLsp.e2e.ts
test/specs/auraLsp.e2e.ts
test/specs/deployAndRetrieve.e2e.ts
test/specs/lwcLsp.e2e.ts
test/specs/visualForceLsp.e2e.ts
* Added VSCODE_VERSION and SPEC_FILES environment settings
* In authorizeDevHub() I added code to "type in" the name of the scratch org.  This way, if there are many scratch orgs and the one you are searching for isn't visible, typing will filter by name and it will appear.
* In testSetup.ts, I added code which verifies that the alias and user name are set, and verifies there is a corresponding match in the org list.

added additional test suites

---

test/utilities/screenshot.ts

After running the full suite of current tests, we realized the spec title can also [cause failures](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5190653634/jobs/9357391423)!
@W-13013918@
Screenshot upload failed because of an un-sanitized spec title directory.
Successfully uploads: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5191554690

test: sanitize spec title too

---

test/testSetup.ts

Adding more duration pause while executing `SFDX:Create Project`. Helps the e2e test suite to run successfully.
How To test:
1. Paste this branch in second field i.e. **Set the branch to use for automation tests** of End To End Test manual workflow in salesforcedx-vscode extensions Github Actions. 
2. Choose initialTestSuite.e2e.ts from the drop down to select the test to run.
AC:
All tests within the testsuite should pass.

fix: remote run InitialTestSuite

---

test/specs/visualforceLsp.e2e.ts
test/testSetup.ts

In this PR I increase the pause after the creation of a project so TestSetup.setUp() passes
- [5660238387](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5660238387)
- [5660324254](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5660324254)
- [5660325441](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5660325441)
- Set up the testing environment passing on all suites in [run 15339140679](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5660531888/job/15339140679)
@W-13743884@

fix for TestSetup.setUp() 

---

test/specs/deployAndRetrieve.e2e.ts

Makes sure deployAndRetrieve.e2e.ts successfully passes on remote GHA
How to test:
Go to the [End to End Tests Workflow](https://github.com/forcedotcom/salesforcedx-vscode/actions/workflows/e2e.yml) in salesforcedx-vscode repo
Paste the PR's branch (cristi/dr-on-remote) in the second field of the Run workflow dropdown (Set the branch to use for automation tests)
Choose deployAndRetrieve.e2e.ts test from the dropdown to select the test to run.
AC:
- [158](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5813955391)
- [175](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5824046171)
- [176](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5824327251)
- …

Fixes for deploy and retrieve on remote GHA

---

test/specs/pushAndPull.e2e.ts

Makes sure pushAndPull.e2e.ts successfully passes on remote GHA
How to test:
Go to the [End to End Tests Workflow](https://github.com/forcedotcom/salesforcedx-vscode/actions/workflows/e2e.yml) in salesforcedx-vscode repo
Paste the PR's branch (cristi/push-pull-on-remote) in the second field of the Run workflow dropdown (Set the branch to use for automation tests)
Choose pushAndPull.e2e.ts test from the dropdown to select the test to run.
AC:
- [209](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5827615892)
- [214](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5827768696)
- [223](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5828384737)
- …

Fixes for Push and Pull on remote

---

test/specs/authentication.e2e.ts
test/testSetup.ts
test/utilities/terminalView.ts

Makes sure authentication.e2e.ts successfully passes on remote GHA
How to test:
Go to the [End to End Tests Workflow](https://github.com/forcedotcom/salesforcedx-vscode/actions/workflows/e2e.yml) in salesforcedx-vscode repo
Paste the PR's branch (cristi/auth-on-remote) in the second field of the Run workflow dropdown (Set the branch to use for automation tests)
Choose authentication.e2e.ts test from the dropdown to select the test to run.
AC:
- [260](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5845433222)
- [262](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5845520206)
- [263](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5845521757)
@W-13743956@

Fixes for Authentication on remote

---

test/specs/apexReplayDebugger.e2e.ts
test/utilities/apexUtils.ts

Makes sure apexReplayDebugger.e2e.ts successfully passes on remote GHA
How to test:
Go to the [End to End Tests Workflow](https://github.com/forcedotcom/salesforcedx-vscode/actions/workflows/e2e.yml) in salesforcedx-vscode repo
Paste the PR's branch (cristi/ard-on-remote) in the second field of the Run workflow dropdown (Set the branch to use for automation tests)
Choose apexReplayDebugger.e2e.ts test from the dropdown to select the test to run.
AC:
- [298](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5862747595)
- [299](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5862748433)
- [300](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5862749111)
@W-13743985@

Fixes for Apex Replay Debugger on remote

---

test/specs/debugApexTests.e2e.ts
test/utilities/apexUtils.ts
test/utilities/sideBar.ts

(1) Go to the [End to End Tests Workflow](https://github.com/forcedotcom/salesforcedx-vscode/actions/workflows/e2e.yml) in salesforcedx-vscode repo
(2) Paste the PR's branch (daphne/debugApexTests-on-remote) in the second field of the Run workflow dropdown (Set the branch to use for automation tests)
(3) Choose debugApexTests.e2e.ts test from the dropdown to select the test to run.
AC:
(1) Added logic to trigger refreshment of the APEX TESTS section of the sidebar if tests do not show up.
(2) Used notificationIsPresentWithTimeout() instead of notificationIsPresent().  As a result of the change, removed all calls to waitForNotificationToGoAway().
(3) Uncovered the 'Debug' button that was previously covered by the command palette due to small VSCode window size in …

debugApexTests.test.ts runs successfully on remote

---

test/specs/runApexTests.e2e.ts

The runApexTests.test.ts and debugApexTests.test.ts files share several changes that allowed them to run successfully on Remote.  One of those shared changes was clicking the Refresh button up to 3 times in order for the Apex tests to show up in the Test sidebar.  Because it is a shared change, I created a utility function with the shared change while working on debugApexTests.test.ts and now came back to modify runApexTests.test.ts to call the utility function.
• [347](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5904632690)
• [348](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5904842209)
• [349](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/5904847094)

Refactor runApexTests.test.ts to call retrieveAllApexTestItemsFromSidebar() utility function

---

test/specs/sObjectsDefinitions.e2e.ts

(1) Go to the [End to End Tests Workflow](https://github.com/forcedotcom/salesforcedx-vscode/actions/workflows/e2e.yml) in salesforcedx-vscode repo
(2) Paste the PR's branch (daphne/sObjsDefinitions-on-remote) in the second field of the Run workflow dropdown (Set the branch to use for automation tests)
(3) Choose sObjectsDefinitions.e2e.ts test from the dropdown to select the test to run.
AC:
(1) Used notificationIsPresentWithTimeout() instead of attemptToFindNotification().  This way, the program searches for notifications within a set period of time instead of within a set number of tries.
(2) Used getVisibleChild() instead of findChildItem() for finding Customer__c.object-meta.xml and Product__c.object-meta.xml within their parent folders.  This is because …

sObjectsDefinitions.test.ts runs successfully on remote

---

test/specs/visualforceLsp.e2e.ts

Previously, the Visualforce E2E test sometimes failed in the "Verify Extension is Running" step, which checks that the Visualforce extension is present in "Developer: Show Running Extensions".  The Visualforce extension is in fact started up but hidden at the bottom of the list and only accessible using the scroll bar.  To fix the problem, I added four "View: Zoom Out" lines before checking for the Visualforce extension in the list of running extensions so that all the running extensions are visible during the check.

Visualforce E2E Test - zoom out to make Visualforce extension visible in running extensions

---

test/specs/apexReplayDebugger.e2e.ts
test/specs/authentication.e2e.ts
test/specs/debugApexTests.e2e.ts
test/specs/deployAndRetrieve.e2e.ts
test/specs/manifestBuilder.e2e.ts
test/specs/pushAndPull.e2e.ts
test/specs/runApexTests.e2e.ts
test/specs/sObjectsDefinitions.e2e.ts
test/specs/templates.e2e.ts
test/specs/trailApexReplayDebugger.e2e.ts
test/testSetup.ts
test/utilities/miscellaneous.ts

Our E2E tests rely on notification checking to make sure that commands are successfully run.  This PR improves the consistency of the notification checking process so that E2E tests don't frequently fail during this step.
In every run of all E2E tests, there were 1-3 jobs that would fail during notification checking because of the following reasons:
1. The notification is fading away / already disappeared before the check was conducted
2. The command is still running and the success notification did not appear yet
This is happening because the amount of time it takes for a command to finish running fluctuates between different test runs and different OS.  It's difficult to catch the exact timing of the notifications' presence.
All runs of E2E tests stop failing during the notifications …

Improve consistency of notification checking in E2E tests

---

test/specs/apexLsp.e2e.ts
test/specs/auraLsp.e2e.ts
test/specs/lwcLsp.e2e.ts
test/specs/visualforceLsp.e2e.ts
test/utilities/extensionUtils.ts

This is just a refactor of `findExtensionInRunningExtensionsList()` in order to check for the right id in the html and not what's displayed

chore: refactor findExtensionInRunningExtensionsList

---

test/TBD/lwcLsp.e2e.ts
test/specs/anInitialSuite.e2e.ts
test/specs/apexLsp.e2e.ts
test/specs/apexReplayDebugger.e2e.ts
test/specs/auraLsp.e2e.ts
test/specs/authentication.e2e.ts
test/specs/deployAndRetrieve.e2e.ts
test/specs/manifestBuilder.e2e.ts
test/specs/pushAndPull.e2e.ts
test/specs/templates.e2e.ts
test/specs/trailApexReplayDebugger.e2e.ts
test/specs/visualforceLsp.e2e.ts
test/testSetup.ts
test/utilities/apexUtils.ts
test/utilities/commandPrompt.ts
test/utilities/extensionUtils.ts

This PR contains fixes for the most common setup errors that are causing E2E tests to fail.  Here is what got fixed:
1. **Problem**: "element not interactable" when running "SFDX: Create Project" to start each E2E test because the CLI Integration extension is not yet loaded.
**Solution**: Run "SFDX: Create Project" to trigger the CLI Integration extension to load, then hit Escape and check every 10 seconds that the extension is actually loaded.  After the extension is activated, run "SFDX: Create Project" again to completion.
2. **Problem**: "Quick Pick Item SFDX: ______ was not found" after running "Developer: Reload Window".
**Solution**: Every time "Developer: Reload Window" is run, wait for all extensions to start up and confirm that they are activated before they are called.
3. …

Fix Common Setup Errors in E2E Tests

---

test/specs/apexLsp.e2e.ts
test/specs/lwcLsp.e2e.ts
test/specs/trailApexReplayDebugger.e2e.ts
test/specs/visualforceLsp.e2e.ts

- Fixes `coordinates is not iterable` error that would come up every now and then when using `textEditor.moveCursor(r,c)` or `textEditor.typeTextAt(r,c)`
- skips `Visualforce LSP - Go to definition` step as it's not testing anything right now because the feature itself is not working
@W-14499848@
- 606: [End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/6909363165/job/18800545331)
- 607: [End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/6909537034)

Cristi: W-14499848 - 'coordinates is not iterable' error

---

test/specs/deployAndRetrieve.e2e.ts

These steps had been skipped because of failures after testing against vsixes. After my previous PR (#61) they're working again
- 175: [Core End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/7105905534)
- 176: [Core End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/7107017802)
- 177: [Core End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/7118164437)

Un-skip skipped steps in deployAndRetrieve.e2e.ts

---

test/setup/anInitialSetUp.e2e.ts
test/specs/apexLsp.e2e.ts
test/specs/apexReplayDebugger.e2e.ts
test/specs/lwcLsp.e2e.ts
test/specs/pushAndPull.e2e.ts
test/testSetup.ts
test/utilities/miscellaneous.ts

This PR contains two main improvements to the E2E tests:
1. Previously, we were seeing a "coordinates is not iterable" error in about 80% of our Ubuntu test runs of the LWC LSP E2E test.  This PR replaces the `.typeTextAt()` function with `browser.keys` in order to work around that issue.
2. In our code, several CLI commands are called using `exec()` to be run directly in the Terminal.  The following CLI commands are changed from SFDX-style to SF-style:
a. `auth:sfdxurl:store` -> `org:login:sfdx-url`
b. `force:user:create` -> `org:create:user`
c. `force:org:delete` -> `org:delete:scratch`
d. `force:org:display` -> `org:display`
e. `force:org:list` -> `org:list`
f. `force:org:create` -> `org:create:scratch`
Passing E2E test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/run …

E2E test improvements - (1) fix for "coordinates is not iterable" error in LWC LSP (2) SFDX -> SF

---

test/specs/apexLsp.e2e.ts
test/utilities/extensionUtils.ts

This flapper has been around for a few months, and it was mostly present in **ApexLsp.e2e.ts** during the **Verify Extension is Running** step.  The cause of this flapper was in **extensionUtils.ts** in the `findExtensionInRunningExtensionsList()` function - after the extension is found, the for loop kept going and searching for the extension rather than breaking out of the loop, which caused a stale element and this error message.
What was fixed: Add a `break` in the for loop after the extension is found.
@W-14498987@
Passing E2E test runs:
1. Apex E2E Tests #84: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/7704042747
2. Apex E2E Tests #85: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/7704043867
3. Apex E2E Tests #86: …

fix: eliminate 'unknown error: unhandled inspector error: {"code":-32000,"message":"No node with given id found"}' flapper

---

test/specs/auraLsp.e2e.ts

This PR contains fixes for flappers in the Aura E2E test that prevent it from running successfully on VSIXs.
What got fixed:
1. The Aura LSP indexes existing Aura files when the Aura extension is activated, but the Aura component that we use for Go to Definition did not get indexed because it was created after the indexing happened.  I added a reload after the Aura component is created so that the Aura LSP would restart and redo the indexing, capturing the new component.
2. The `textEditor.getCoordinates()` function call in Go to Definition and the `textEditor.typeTextAt()` function call in Autocompletion cause a `coordinates is not iterable` error when the E2E test is run on Ubuntu.  This PR contains workarounds using `browser.keys()` to recreate the same functionality and get around the …

fix: Aura E2E Test runs on VSIXs

---

test/specs/deployAndRetrieve.e2e.ts

The output tab validation started failing for the SFDX: Delete This from Project and Org command as it no longer includes the project path. This PR fixes that
E2E run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/8693621912

fix: remove project path from output tab text validation

---

test/specs/miscellaneous.e2e.ts
test/testSetup.ts
test/wdio.conf.ts

Disable auto-update in vscode for e2e tests
- Modifies LWC HTML snippets insertion from Command Palette instead of typing for more accuracy
- Gets rid of `disableCommandCenter()` in favor of `'window.commandCenter': false` in wdio.conf.ts
- Sets `'extensions.autoUpdate': false` in wdio.conf.ts with `VSCodeOptions.userSettings` property
[W-15736459](https://gus.lightning.force.com/a07EE00001rB6zQYAS)

fix: turn off setting to auto update extensions

---

test/specs/anInitialSuite.e2e.ts
test/testSetup.ts

In this PR we add a check for uncaught errors as part of the tearDown step that runs at the end of each test suite
[W-15471367](https://gus.lightning.force.com/a07EE00001oEl72YAC)
Test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9321356263/job/25660154165 ✅

feat: check for uncaught errors in Running Extensions view at the end of each suite

---

test/specs/anInitialSuite.e2e.ts
test/utilities/extensionUtils.ts

To avoid an uncaught error in the ESLint extension (which the LWC extension is no longer dependent on) the E2E tests now only install the Salesforce extensions individually, without any extension packs that contain third-party extensions.  This workaround will take place until we complete the migration of E2E tests to ESM and can start testing on the latest VSCode version.
@W-16084277@
E2E test run: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9702077940
_Note: There are some flappers during the extensions VSIX installation process but all the E2E tests except AnInitialSuite pass for at least 2 OS's.  (AnInitialSuite keeps on flapping during the tear down step.)_

chore: do not install Salesforce Extension Pack and Salesforce Extension Pack Expanded in E2E

---

test/specs/apexLsp.e2e.ts
test/testSetup.ts
test/utilities/apexUtils.ts
test/utilities/extensionUtils.ts
test/utilities/miscellaneous.ts
test/utilities/outputView.ts

E2E tests were always failing with `Error: Quick pick item SFDX: Set a Default Org was not found` on windows. Tests can now run past that point and eventually (considering flappers like the rest of os's) make it to tear down.
@W-16164065@
[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/9812786679)

fix: make e2e tests run past setup step on windows

---

package-lock.json
package.json
test/specs/miscellaneous.e2e.ts
test/utilities/extensionUtils.ts

Made the following changes to get E2E tests running on our new minimum supported VSCode version 1.86.0:
1. Checks for the Running Extensions tab in a different selector based on whether VSCode version is >=1.90.0
2. Checks for "Snippets: Configure Snippets" vs. "Snippets: Configure User Snippets" based on whether VSCode version is >=1.92.0
@W-16361200@
E2E test runs:
1. stable: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10325834691
2. 1.86.0: https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10325829201

feat: add support for running E2E tests on VSCode version 1.86.0
